-- First, remove the table if it exists
drop table if exists books;

-- Create the table anew
create table books (
  id INTEGER primary key generated by default as identity,
  title text,
  url text,
  rating INTEGER,
  description VARCHAR(150)
);

-- insert some test data
-- Using a multi-row insert statement here
insert into books (title, url, rating, description)
values
  ('Sam', 'https://sam.com', 3, 'Website for Sam'),
  ('Ham', 'https://ham.com', 2, 'Website for Ham'),
  ('Ram', 'https://ram.com', 5, 'Website for Ram');